### PR TITLE
Updates CI configuration

### PR DESCRIPTION
**Pull request by helrond**
- Updates README
- Updates Travis CI configs
- Adds issue templates

Note there is no development branch for this repo, since it is a template.

### CODE REVIEW

**Comment by bonniegee** [comment]
The `entrypoint.sh` script is using `8000` here, and not a variable--does it make sense to tie these together (as you mentioned in the Aquila PR) in this template?

**Comment by helrond** [comment]
So I think the path to do that would be to add an environment variable in the docker-compose file, which could then be picked up by entrypoint.sh. I'm unsure if that's better or worse than hardcoding the port number. Thoughts?

**Comment by bonniegee** [comment]
I think hardcoding the port number in entrypoint is fine, but if it needs to match up with the port elsewhere it may be worth mentioning in the README? (Particularly because this is a template--not sure if that would need to extend to other applications.)

**Comment by helrond** [comment]
Well it needs to match (at least) the port you're listening on in the Django service of the compose file. Ideally I'd love there to be a way to keep port numbers in Travis and Docker aligned with a single variable but that may not be possible.

**Comment by helrond** [comment]
OK, so after a bit of experimentation I think it's best to let sleeping dogs lie on this one for right now. There are improvements we can make on the current setup, but they are all tied into environment variables which are available in different environments (local, CI and deploy) so I think it makes sense to solidify deploy patterns before trying to make a universally-workable move here. I've added #5 to track this.

In the meantime I've updated the README with information about these ports and where they are.

**Review by p-galligan — APPROVED** [review]

**Review by HaSistrunk — APPROVED** [review]

**Review by bonniegee — APPROVED** [review]

**Pull request merged**
